---
sidebar: sidebar 
permalink: get-help.html 
keywords: get help, get support, knowledgebase, discord, phone, web, ticket, contact support, support ticket 
summary: NetApp은 다양한 방법으로 Trident를 지원합니다. 불협화채널 등 광범위한 자아 지원 옵션이 연중 무휴로 제공됩니다. 
---
= 지원
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp은 Astra Trident를 다양한 방법으로 지원합니다. 기술 자료(KB) 기사 및 불화 채널 같은 광범위한 무료 셀프 지원 옵션이 24x7 제공됩니다.



== Astra Trident 지원 라이프사이클

Astra Trident는 버전에 따라 3가지 수준의 지원을 제공합니다. 을 link:https://mysupport.netapp.com/site/info/version-support["정의를 위한 NetApp 소프트웨어 버전 지원"^]참조하십시오.

완벽한 지원:: Astra Trident는 릴리즈부터 12개월간 모든 지원을 제공합니다.
제한된 지원:: Astra Trident는 릴리즈부터 13~24개월까지 제한적으로 지원을 제공합니다.
자가 지원:: Astra Trident 문서는 릴리즈일로부터 25~36개월 동안 사용할 수 있습니다.


[cols="1, 1, 1, 1"]
|===
| 버전 | 완벽한 지원 | 제한된 지원 | 자가 지원 


 a| 
link:https://docs.netapp.com/us-en/trident/index.html["24.06"^]
| 2025년 6월 | 2026년 6월 | 2027년 6월 


 a| 
link:https://docs.netapp.com/us-en/trident/index.html["24.02"^]
| -- | 2026년 2월 | 2027년 2월 


 a| 
link:https://docs.netapp.com/us-en/trident-2310/index.html["23.10"^]
| -- | 2025년 10월 | 2026년 10월 


 a| 
link:https://docs.netapp.com/us-en/trident-2307/index.html["23.07"^]
| -- | 2025년 7월 | 2026년 7월 


 a| 
link:https://docs.netapp.com/us-en/trident-2304/index.html["23.04"^]
| -- | 2025년 4월 | 2026년 4월 


 a| 
link:https://docs.netapp.com/us-en/trident-2301/index.html["23.01"^]
| -- | -- | 2026년 1월 


 a| 
link:https://docs.netapp.com/us-en/trident-2210/index.html["22.10"^]
| -- | -- | 2025년 10월 


 a| 
link:https://docs.netapp.com/us-en/trident-2207/index.html["22.07"^]
| -- | -- | 2025년 7월 


 a| 
link:https://docs.netapp.com/us-en/trident-2204/index.html["22.04"^]
| -- | -- | 2025년 4월 
|===


== 자가 지원

전체 문제 해결 문서 목록은 을 https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes["NetApp Knowledgebase(로그인 필요)"^]참조하십시오. Astra 관련 문제 해결 정보에 대해서도 확인할 수 https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra["여기"^] 있습니다.



== 커뮤니티 지원

Astra에는 컨테이너 사용자의 활발한 공공 커뮤니티(Astra Trident 개발자 포함)가 link:https://discord.gg/NetApp["불화 채널"^]있습니다. 프로젝트에 대한 일반적인 질문을 하고 비슷한 생각을 가진 동료와 관련 주제를 논의할 수 있는 좋은 장소입니다.



== NetApp 기술 지원

Astra Trident에 대한 지원이 필요하면 를 사용하여 지원 번들을 생성한 `tridentctl logs -a -n trident` 후 로 `NetApp Support <Getting Help>`전송합니다.



== 를 참조하십시오

* link:https://cloud.netapp.com/blog/topic/astra["Astra 블로그"^]
* link:https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Astra Trident 블로그"^]
* link:https://cloud.netapp.com/kubernetes-hub["쿠버네티스 허브"^]
* link:https://netapp.io/["NetApp.IO를 참조하십시오"^]

