---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: ONTAP SAN 드라이버를 사용하여 ONTAP 백엔드를 구성하는 방법에 대해 알아보십시오. 
---
= ONTAP SAN 드라이버 개요
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 및 Cloud Volumes ONTAP SAN 드라이버를 사용하여 ONTAP 백엔드를 구성하는 방법에 대해 알아보십시오.



== ONTAP SAN 드라이버 세부 정보입니다

Astra Trident는 ONTAP 클러스터와 통신할 수 있는 다음과 같은 SAN 스토리지 드라이버를 제공합니다. 지원되는 액세스 모드는 _ReadWriteOnce_(RWO), _ReadOnlyMany_(ROX), _ReadWriteMany_(rwx), _ReadWriteOncePod_(RWOP)입니다.


IMPORTANT: 보호, 복구 및 이동성을 위해 Astra Control을 사용하는 경우 를 참조하십시오.<<Astra Control 드라이버 호환성>>

[cols="2, 1, 1, 2, 2"]
|===
| 드라이버 | 프로토콜 | 볼륨 모드 | 액세스 모드가 지원됩니다 | 지원되는 파일 시스템 


| `ontap-san`  a| 
iSCSI
 a| 
블록
 a| 
RWO, ROX, rwx, RWOP
 a| 
파일 시스템이 없습니다. 원시 블록 디바이스입니다



| `ontap-san`  a| 
iSCSI
 a| 
파일 시스템
 a| 
RWO, 공화당

파일 시스템 볼륨 모드에서는 ROX 및 rwx를 사용할 수 없습니다.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san`  a| 
NVMe/TCP

을 <<NVMe/TCP에 대한 추가 고려사항>>참조하십시오.
 a| 
블록
 a| 
RWO, ROX, rwx, RWOP
 a| 
파일 시스템이 없습니다. 원시 블록 디바이스입니다



| `ontap-san`  a| 
NVMe/TCP

을 <<NVMe/TCP에 대한 추가 고려사항>>참조하십시오.
 a| 
파일 시스템
 a| 
RWO, 공화당

파일 시스템 볼륨 모드에서는 ROX 및 rwx를 사용할 수 없습니다.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
iSCSI
 a| 
블록
 a| 
RWO, ROX, rwx, RWOP
 a| 
파일 시스템이 없습니다. 원시 블록 디바이스입니다



| `ontap-san-economy`  a| 
iSCSI
 a| 
파일 시스템
 a| 
RWO, 공화당

파일 시스템 볼륨 모드에서는 ROX 및 rwx를 사용할 수 없습니다.
 a| 
`xfs`, `ext3`, `ext4`

|===


=== Astra Control 드라이버 호환성

Astra Control은 `ontap-nas-flexgroup`, 및 `ontap-san` 드라이버로 생성된 볼륨에 대한 원활한 보호, 재해 복구 및 이동성(Kubernetes 클러스터 간에 볼륨 이동)을 제공합니다 `ontap-nas`. 자세한 내용은 을 link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Astra Control 복제 사전 요구 사항"^] 참조하십시오.

[WARNING]
====
*  `ontap-san-economy`영구 볼륨 사용률 수가 보다 높을 것으로 예상되는 경우에만 link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["지원되는 ONTAP 볼륨 제한"^]사용합니다.
*  `ontap-nas-economy`영구 볼륨 사용 횟수가 다음보다  크고 `ontap-san-economy` 드라이버를 사용할 수 없는 경우에만 link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["지원되는 ONTAP 볼륨 제한"^]사용합니다.
* 데이터 보호, 재해 복구 또는 이동성이 필요할 것으로 예상되는 경우에는 사용하지 마십시오 `ontap-nas-economy`.


====


== 사용자 권한

Astra Trident은 ONTAP 또는 SVM 관리자로 실행해야 하며, 일반적으로 클러스터 사용자나 `vsadmin` SVM 사용자 또는 동일한 역할을 가진 다른 이름의 사용자를 사용합니다 `admin`. Amazon FSx for NetApp ONTAP 구축의 경우 Astra Trident는 클러스터 사용자 `vsadmin` 또는 SVM 사용자를 사용하여 ONTAP 또는 SVM 관리자로 실행되거나 동일한 역할을 가진 다른 이름의 사용자로 실행되어야 `fsxadmin` 합니다.  `fsxadmin`사용자는 클러스터 관리자를 제한적으로 대체합니다.


NOTE:  `limitAggregateUsage`매개 변수를 사용하려면 클러스터 관리 권한이 필요합니다. Amazon FSx for NetApp ONTAP를 Astra Trident와 함께 사용할 때 `limitAggregateUsage` 매개 변수는 및 `fsxadmin` 사용자 계정에서 작동하지 `vsadmin` 않습니다. 이 매개 변수를 지정하면 구성 작업이 실패합니다.

Trident 드라이버가 사용할 수 있는 더 제한적인 역할을 ONTAP 내에 만들 수 있지만 권장하지 않습니다. Trident의 대부분의 새로운 릴리즈에서는 추가 API를 호출하므로 업그레이드가 어렵고 오류가 발생하기 쉽습니다.



== NVMe/TCP에 대한 추가 고려사항

Astra Trident은 다음과 같은 드라이버를 사용하여 NVMe(Non-volatile Memory Express) 프로토콜을 `ontap-san` 지원합니다.

* IPv6 를 참조하십시오
* NVMe 볼륨의 스냅샷 및 클론
* NVMe 볼륨 크기 조정
* Astra Trident 외부에서 생성된 NVMe 볼륨을 가져와 Astra Trident로 라이프사이클을 관리할 수 있음
* NVMe 네이티브 다중 경로
* K8 노드의 정상 또는 비정상적으로 종료 (24.06)


Astra Trident는 다음을 지원하지 않습니다.

* NVMe에서 기본적으로 지원하는 DH-HMAC-CHAP입니다
* DM(Device Mapper) 경로 다중화
* LUKS 암호화

